CREATE TABLE az.Progetto(
CUP INTEGER,
Nome VARCHAR(20),
Budget FLOAT,
Attivo CHAR(1) CHECK(Attivo IN ('S', 'N')),
ReferenteScientifico INTEGER,
Responsabile INTEGER,
Lab1 INTEGER,
Lab2 INTEGER,
Lab3 INTEGER,

CONSTRAINT PKP1 PRIMARY KEY (CUP),
CONSTRAINT UNQP1 UNIQUE (Nome),
CONSTRAINT FKP1 FOREIGN KEY(ReferenteScientifico) REFERENCES az.Impiegato(CodImpiegato),
CONSTRAINT FKP2 FOREIGN KEY(Responsabile) REFERENCES az.Impiegato(CodImpiegato),
CONSTRAINT FKP3 FOREIGN KEY(Lab1) REFERENCES az.Laboratorio(CodLab),
CONSTRAINT FKP4 FOREIGN KEY(Lab2) REFERENCES az.Laboratorio(CodLab),
CONSTRAINT FKP5 FOREIGN KEY(Lab2) REFERENCES az.Laboratorio(CodLab));